"""Mirror check: the numpy warp must agree with the reference
implementation to ~1e-9 on a shared fixture. Run this after any change
to either implementation. Emits the fixture that downstream suites
cross-check."""

import json
import os
import sys

import numpy as np

from warp import unwarp_points, warp_points

HERE = os.path.dirname(os.path.abspath(__file__))
MESH = os.path.join(HERE, "mesh", "uncrumple-beam-1.json")


def main() -> None:
    mesh = json.load(open(MESH))
    pos = np.array(mesh["positions"], dtype=np.float64).reshape(-1, 3)
    assert mesh["meshId"] == "uncrumple-beam/1", mesh["meshId"]
    lo, hi = pos.min(axis=0), pos.max(axis=0)
    unit = (pos - lo) / (hi - lo)
    c = np.array([0.21, -0.33, 0.12, 0.4, -0.18, 0.27, -0.09, 0.31, -0.22])
    warped = warp_points(unit[:64], c)
    back = unwarp_points(warped, c)
    err = float(np.abs(back - unit[:64]).max())
    print(f"roundtrip worst={err:.2e}")
    assert err < 1e-6, err
    fixture = {
        "_provenance": "generated by uncrease/mirror.py; cross-checked downstream",
        "meshId": mesh["meshId"],
        "coeffs": c.tolist(),
        "input": unit[:8].tolist(),
        "output": warp_points(unit[:8], c).tolist(),
    }
    os.makedirs(os.path.join(HERE, "fixtures"), exist_ok=True)
    with open(os.path.join(HERE, "fixtures", "mirror.json"), "w") as f:
        json.dump(fixture, f)
    print("fixtures/mirror.json written")


if __name__ == "__main__":
    sys.exit(main())
